---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubegame.systemcraftsman.com
  resources:
  - avatars
  - games
  - worlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubegame.systemcraftsman.com
  resources:
  - avatars/finalizers
  - games/finalizers
  - worlds/finalizers
  verbs:
  - update
- apiGroups:
  - kubegame.systemcraftsman.com
  resources:
  - avatars/status
  - games/status
  - worlds/status
  verbs:
  - get
  - patch
  - update
