# permissions for end users to edit worlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: world-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubegame
    app.kubernetes.io/part-of: kubegame
    app.kubernetes.io/managed-by: kustomize
  name: world-editor-role
rules:
- apiGroups:
  - kubegame.systemcraftsman.com
  resources:
  - worlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubegame.systemcraftsman.com
  resources:
  - worlds/status
  verbs:
  - get
