apiVersion: kubegame.systemcraftsman.com/v1alpha1
kind: ItemCatalog
metadata:
  labels:
    app.kubernetes.io/name: itemcatalog
    app.kubernetes.io/instance: itemcatalog-sample
    app.kubernetes.io/part-of: kubegame
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubegame
  name: itemcatalog-sample
spec:
  game: oasis
  items:
    - name: "Iron Sword"
      category: "Equipment"
      rarity: "Common"
      stackable: false
      effects:
        - attribute: "strength"
          modifier: "+5"
