## Append samples of your project ##
resources:
- _v1alpha1_game.yaml
- _v1alpha1_world.yaml
- _v1alpha1_avatar.yaml
- _v1alpha1_area.yaml
- _v1alpha1_item.yaml
- kubegame.systemcraftsman.com_v1alpha1_currency.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
